[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
pluginYml = { id = "de.eldoria.plugin-yml.bukkit", version.ref = "plugin_yml" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "run_paper" }

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
cloud = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud" }
worldedit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version.ref = "worldedit" }

[versions]
minecraft = "1.21.4"
paper = "1.21.4-R0.1-SNAPSHOT"
kotlin = "2.1.0"
plugin_yml = "0.6.0"
run_paper = "2.3.1"
cloud = "2.0.0-beta.10"
worldedit = "7.3.10-SNAPSHOT"